kind: Service
apiVersion: v1
metadata:
  labels:
{{ include "nodeapp.labels.stakater" . | indent 4 }}
{{ include "nodeapp.labels.chart" . | indent 4 }}
    k8sapp: stakater-nodeapp   # label used by service monitor
  name: {{ template "nodeapp.name" . }}
spec:
  selector:
{{ toYaml .Values.nodeapp.deployment.podLabels | indent 4 }}
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 5000